name: SidewalkSlam

on:
  push:
    branches:
      - "master"
      - "actions-test"
jobs:          
  buildOnLinux:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildName:
          - SidewalkSlam
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-builder@v4
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          buildName: ${{ matrix.buildName }}
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  deployToItch:
    needs: [buildOnLinux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download StandaloneWindows64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
      - name: Download StandaloneLinux64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneLinux64
          path: build/StandaloneLinux64
      - name: Setup butler
        uses: remarkablegames/setup-butler@v1
      - name: Upload Linux to itch.io
        run: butler push StandaloneLinux64 timo654/sidewalkslam:linux
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
       - name: Upload Windows to itch.io
        run: butler push StandaloneWindows64 timo654/sidewalkslam:windows
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}